image: Visual Studio 2017
environment:
  PREFIX: C:\Deps
  FLEXBISON_VERSION: 2.4.12
  matrix:
    - COMPILER: msvc
    - COMPILER: msys2
platform:
  - x86
  - x64
cache:
  - '%PREFIX% -> .appveyor.yml'
  - c:\tools\vcpkg\installed\
install:
  - |-
    if %COMPILER% NEQ msvc set MSVC=rem
    if %COMPILER% NEQ msys2 set MSYS2=rem
    if exist %PREFIX% set DEP=rem
  - |-
    if %PLATFORM%==x64 set MSVC_GENERATOR_APPEND= Win64
  - |-
    if %PLATFORM%==x86 (set MSYS2_PLATFORM=i686) else set MSYS2_PLATFORM=x86_64
    if %PLATFORM%==x86 (set MSYS2_MSYSTEM=MINGW32) else set MSYS2_MSYSTEM=MINGW64
  - |-
    %DEP% cd %TEMP%
    %DEP% mkdir %PREFIX%
    %MSYS2% set MSYS2_BASH=C:\msys64\usr\bin\bash -lc
  # MSVC
  - |-
    %MSVC% %DEP% appveyor DownloadFile https://github.com/lexxmark/winflexbison/releases/download/v%FLEXBISON_VERSION%/win_flex_bison-%FLEXBISON_VERSION%.zip
    %MSVC% %DEP% 7z x win_flex_bison-%FLEXBISON_VERSION%.zip -o%PREFIX%\win_flex_bison > nul
    %MSVC% vcpkg install sdl2:%PLATFORM%-windows sdl2-image:%PLATFORM%-windows sdl2-mixer:%PLATFORM%-windows pugixml:%PLATFORM%-windows glew:%PLATFORM%-windows
  # MSYS2
  - |-
    %MSYS2% %MSYS2_BASH% "pacman -S --needed --noconfirm mingw-w64-%MSYS2_PLATFORM%-cmake mingw-w64-%MSYS2_PLATFORM%-SDL2 mingw-w64-%MSYS2_PLATFORM%-SDL2_image mingw-w64-%MSYS2_PLATFORM%-SDL2_mixer mingw-w64-%MSYS2_PLATFORM%-glew mingw-w64-%MSYS2_PLATFORM%-pugixml"
before_build:
  - |-
    mkdir %APPVEYOR_BUILD_FOLDER%\build
    cd %APPVEYOR_BUILD_FOLDER%\build
  # Visual Studio
  - |-
    %MSVC% cmake -G"Visual Studio 15 2017%MSVC_GENERATOR_APPEND%" -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_PROGRAM_PATH=%PREFIX%\win_flex_bison ..
  # MSYS2
  - |-
    %MSYS2% %MSYS2_BASH% "MSYSTEM=%MSYS2_MSYSTEM% . /etc/profile && cd '%CD%' && cmake -DCMAKE_PREFIX_PATH='%PREFIX%' -G'MSYS Makefiles' .."
build_script:
  # Visual Studio
  - |-
    %MSVC% cmake --build . --config Release
  # MSYS2
  - |-
    %MSYS2% %MSYS2_BASH% "MSYSTEM=%MSYS2_MSYSTEM% . /etc/profile && cd '%CD%' && make"
